var jobs = [
	{
		id           : 13,
		name         : "PHP Developer",
		title        : "PHP Web Developer",
		description  : "2+ years of experience<br>Experience of the full software development lifecycle: from requirements gathering and functional specification<br>Strong knowledge of PHP frameworks ( Laravel is must )<br>Good knowledge of front-end technologies, such as JavaScript, jQuery, HTML5, and CSS3<br>Understanding of code versioning tools<br>Understanding of Ajax, JSON<br>Max age 35",
		location     : "Egypt",
		address      : "Media Misr - Cairo, Egypt",
		skills       : ["Software Development","Laravel","PHP","CSS3","HTML5","jQuery","javaScript","AJAX","JSON"],
		experience   : 2,
		company_name : "Nile Multimedia",
		about_company: "Nile Multimedia is an Egyptian Limited Liability Company and in accordance with the provisions Act 159 of 1981, Ratified by the General Authority for Investment No. 1309 of 2007, Commercial No. 27762 and Tax card No. 266-680-976.",
		company_logo : "images/Nile-Multimedia-Egypt-4085-sm.png",
		job_type     : "Full Time",
		salary       : 5000,
		user_id      : 6,
		approved     : true,
		availability : true,
	},{
		id           : 19,
		name         : "Web Developer",
		title        : "PHP Laravel Developer",
		description  : "Design, build, and deploy efficient, testable and reusable PHP applications and modules according to specifications<br>Troubleshoot and maintain new and existing applications and databases<br>Building the backed DB design and APIs<br>Contribute in all phases of the development lifecycle.<br>Write technical documents for projects",
		location     : "Egypt",
		address      : "Mohandessin, Giza",
		skills       : ["Information Technology (IT)","PHP","Back-End","HTML","AJAX","CSS","javaScript","jQuery","Web Design","Web Development","Joomla","Laravel","HTML5","CSS3","Opencart","Magento","Git","MVC"],
		experience   : 1,
		company_name : "PPLMX",
		about_company: "To assign a virtual assistant for our employees to change their lives to better tom, accomplish personal tasks, stabilize their bills and responsibilities, help them raise their kids, motivate them in work, work on improving the family relationship, work on the employee's whole family health specially naturally, work on the employee property, fill any unknown gap the employee might feel that he has no clue how to manage it.",
		company_logo : "images/PPLMX-Egypt-20044-1475157676-sm.PNG",
		job_type     : "Full Time",
		salary       : 3000,
		user_id      : 18,
		approved     : true,
		availability : true,
	},{
		id           : 21,
		name         : "Full Stack Web Developer (PHP / Laravel)",
		title        : "PHP Laravel Developer",
		description  : "More than 2 year experience with PHP/Laravel framework and using Eloquent.<br>Ability to hand-code HTML and CSS.<br>Good understanding of database design basics and MySQL querying.<br>Solid experience with Javascript and one or more JS frameworks.<br>Experience with API design, AJAX-style asynchronous loading and statistical and graphical visualization.<br>Experienced in building and/or consuming web services/APIs.<br>Ability to create and use new libraries.<br>Familiarity with Linux OS and passion for open source technologies",
		location     : "Egypt",
		address      : "Maadi, Cairo",
		skills       : ["PHP","MySQL","Development","Linux","Symfony2","Mongo","Angular","PHP5","Laravel","HTML","CSS","JavaScript","JSON","HTTP","CSS"],
		experience   : 3,
		company_name : "Ebtikar IT",
		about_company: "Ebtikar IT is a multinational company which owns the trademarks of Ebtikar, EbtikarSMS, EbtikarConsulting, EbtikarHost and EbtikarCloud is the biggest web hosting and clouding provider in the MEA region. <br>As a top-notch Production software and Internet services company, Ebtikar IT offers a wide range of solutions to a rapidly increasing valuable clients in the MEA region, Our service portfolio includes : Production accounting and administrative software and analysis of electronic systems & web hosting, hosted applications, cloud computing services, E-governance, E-learning, audio/video streaming, hosted CRM ,VOIP & call center solutions and provides 24/7 round the clock support .",
		company_logo : "images/Ebtikar-IT-Egypt-18198-1487497180-sm.png",
		job_type     : "Full Time",
		salary       : 5000,
		user_id      : 12,
		approved     : true,
		availability : true,
	},{
		id           : 86,
		name         : "PHP Web Developer",
		title        : "PHP Developer",
		description  : "2+ years of experience<br>Experience of the full software development lifecycle: from requirements gathering and functional specification<br>Strong knowledge of PHP frameworks ( Laravel is must )<br>Good knowledge of front-end technologies, such as JavaScript, jQuery, HTML5, and CSS3<br>Understanding of code versioning tools<br>Understanding of Ajax, JSON<br>Max age 35<br>Working from company not home",
		location     : "Egypt",
		address      : "Nasr City, Cairo",
		skills       : ["PHP","MySQL","Development","Linux","Symfony2","Mongo","Angular","PHP5","Laravel","HTML","CSS","JavaScript","JSON","HTTP","CSS"],
		experience   : 3,
		company_name : "360 Codes",
		about_company: "360Code is a promising and emerging company in the software, Programming services providers and Web design and Web development industry that includes a team of professional and expert web developers and graphic designers",
		company_logo : "images/360-codes-Egypt-24815-1495554292-sm.png",
		job_type     : "Full Time",
		salary       : 6000,
		user_id      : 48,
		approved     : true,
		availability : true,
	},{
		id           : 85,
		name         : "WordPress Web Developer - Alexandria",
		title        : "WordPress - Alexandria",
		description  : "Solid knowledge of PHP<br>WordPress theme & plugin development/customization<br>Experience with WooCommerce and its integration with the APIs of payment gateways and shipping companies<br>Solid understanding of WordPress’s template hierarchy and security best practices<br>Front-end development skills like HTML5, CSS3, JavaScript, jQuery, Bootstrap, etc.<br>Previous experience with LAMP development environment and Git version control",
		location     : "Egypt",
		address      : "Glim, Alexandria",
		skills       : ["WordPress","CSS3","HTML5","HTML","PHP","javaScript","jQuery","Bootstrap","FrontEnd"],
		experience   : 3,
		company_name : "Qowwa Inc.",
		about_company: "Qowwa's main focus is to empower local businesses that move the Egyptian community forward by providing them with custom web, mobile, and e-commerce application development.Qowwa’s second focus is to provide website design, development, and management services to local and international clients.",
		company_logo : "images/Qowwa-Inc--Egypt-22246-1485703575-sm.png",
		job_type     : "Full Time",
		salary       : 7000,
		user_id      : 26,
		approved     : true,
		availability : true,
	}
];
